language: c
dist: bionic
script: make && make test
jobs:
  include:
    - name: x86_64_gcc
    - name: x86_gcc
      before_install: sudo apt install -y gcc-multilib g++-multilib
      env: PLATFORMFLAGS=-m32
    - arch: arm64
    - name: arm32_xcompile
      before_install:
        - sudo apt update
        - sudo apt install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
        - sudo apt install -y qemu-user
      env: 
        - PLATFORM_PREFIX=arm-linux-gnueabi-
        - EMULATOR=qemu-arm
    - os: windows
      name: x64_msvc
      script:
        - cd vs2017
        - ./build_x64.cmd && x64/Debug/test.exe
    - os: windows
      name: x86_msvc
      script:
        - cd vs2017
        - ./build_x86.cmd && Win32/Debug/test.exe