name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-amd64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make && make test
  
  test-linux-x86:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platformflags: ["", "-m32"]
    env:
      PLATFORMFLAGS: ${{platformflags}}
    steps:
    - uses: actions/checkout@v2
    - name: install multilib
      run: sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib 
    - name: make
      run: make && make test
      
  test-linux-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
        - arch: arm
          emulator: qemu-arm
          abi: arm-linux-gnueabi
        - arch: aarch64
          emulator: qemu-aarch64
          abi: aarch64-linux-gnu
    env:
      PLATFORM_PREFIX: ${{matrix.abi}}-
      EMULATOR: ${{matrix.emulator}}
    steps:
    - uses: actions/checkout@v2
    - name: install qemu
      run: sudo apt-get install --no-install-recommends -y qemu-user 
    - name: install abi lib
      run: sudo apt-get install --no-install-recommends -y gcc-${{matrix.abi}} g++-${{matrix.abi}} 
    - name: make 
      run: make && make test
      
  test-windows:
    runs-on: windows-2019
    strategy:
      matrix:
        platform: [x86, x64, ARM, ARM64]
        include:
          - platform: x86
            folder: Win32
            native: yes
          - platform: x64
            folder: x64
            native: yes
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: build
        run: msbuild.exe vs2019\stackman.sln /p:Platform=${{matrix.platform}}
      - name: test
        if: ${{ matrix.native == 'yes' }}
        run: vs2019\${{matrix.folder}}\Debug\test.exe
